FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["prime-service.csproj", "."]
RUN dotnet restore "./prime-service.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "prime-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "prime-service.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "prime-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t prime-service . 

# Run Image without env vars
# docker run -it --rm -p 5051:8080 prime-service

#
# docker run -it --rm -p 5051:8080 prime-service -e"App:ConnectionStrings:SQLServerConnection=<SQLSERVER_CONNECTION_STRING>"