name: 03-02-angular-cd-aca

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/angular/angular-devops/*

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  acrName: "az400acrdev"
  image: "az400acrdev.azurecr.io/angular-devops"
  app: "angular-devops-app"
  grp: "az400-dev"
  serviceConnection: wi-az400-dev
  acaenv: "az400acaenv"

stages:
  - template: templates/t-deploy-aca.yaml
    parameters:
      acrName: $(acrName)
      image: $(image)
      app: $(app)
      grp: $(grp)
      serviceConnection: $(serviceConnection)
      acaenv: $(acaenv)
      targetPort: 80
