name: "02-02-angular-ci"

# trigger:
#   branches:
#     include:
#     - master

trigger: none
pr: none

variables:
  nodeVer: "22.14.0"
  dist: angular-devops
  pkg: ngapp
  appRoot: src/angular/angular-devops

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build

    jobs:
      - job: Build
        displayName: Build Angular

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVer)
            displayName: Install Node $(nodeVer)

          - script: npm ci
            displayName: "Install Packages"
            workingDirectory: $(appRoot)

          - script: npm run build
            displayName: "Build"
            workingDirectory: $(appRoot)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(System.DefaultWorkingDirectory)/$(appRoot)/dist/$(dist)/browser"
              ArtifactName: $(pkg)
              publishLocation: "Container"
            displayName: "Publish Artifacts"
