name: 03-02-angular-cd-aca

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/angular/angular-devops/*

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  acrName: "az400acrdev"
  image: "az400acrdev.azurecr.io/angular-devops"
  app: "angular-devops-app"
  grp: "az400-dev"
  serviceConnection: wi-az400-dev
  acaenv: "az400acaenv"

jobs:
  - job: DeployToACA
    displayName: Deploy to ACA
    steps:
      - template: templates/t-deploy-container-app.yaml
        parameters:
          acrName: $(acrName)
          image: $(image)
          app: $(app)
          resourceGroup: $(grp)
          serviceConnection: $(serviceConnection)
          acaEnvironment: $(acaenv)
          targetPort: 80
          override: false
