name: angular-unittest.yml

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeVer: "22.14.0"
  appRoot: src/angular/angular-devops

stages:
  - stage: UnitTest
    displayName: Vitest UnitTest

    jobs:
      - job: Vitest

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVer)
            displayName: Install Node $(nodeVer)

          - task: Cache@2
            displayName: Setup Node Cache
            inputs:
              key: "$(System.DefaultWorkingDirectory)/$(appRoot)/package-lock.json"
              path: "$(System.DefaultWorkingDirectory)/$(appRoot)/node_modules"
              cacheHitVar: "npmCache"

          - script: npm ci
            displayName: npm ci
            workingDirectory: $(appRoot)
            condition: eq(variables['npmCache'],False)

          - script: |
              npx vitest run \
                --coverage \
                --reporter=junit \
                --reporter=default \
                --outputFile.junit=./test-results/vitest-junit.xml
            displayName: Run vitest tests
            workingDirectory: $(appRoot)

          - task: PublishTestResults@2
            displayName: Publish Vitest test results
            condition: succeededOrFailed()
            inputs:
              searchFolder: $(appRoot)/test-results
              testRunTitle: Angular Vitest Tests
              testResultsFormat: JUnit
              testResultsFiles: "vitest-junit.xml"

          - task: PublishCodeCoverageResults@1
            displayName: Publish Vitest coverage
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(appRoot)/coverage/cobertura-coverage.xml"
              reportDirectory: "$(appRoot)/coverage"
              failIfCoverageEmpty: false
