name: "02-04-docker-ci-img"

trigger: none
pr: none

variables:
  imageName: angular-devops
  acr: scACR
  appPath: src/angular/angular-devops/

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "BuildImg"
    displayName: "Build Catalog Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: "$(appPath)dockerfile"
              buildContext: "$(appPath)"

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)
