name: blob-console-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/jobs/blob-spring/*

trigger: none
pr: none

variables:
  path: src/jobs/blob-spring/
  imageName: blob-spring
  acr: conACR

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "BuildImg"
    displayName: "Build Catalog Api Image"
    jobs:
      - job: "Build"
        steps:
          - template: templates/t-build-docker-image.yaml
            parameters:
              acrServiceConnection: $(acr)
              repository: $(imageName)
              dockerfile: "$(path)dockerfile"
              buildContext: $(path)
