name: 05-03-catalog-ci-cd-terraform

trigger: none
pr: none

variables:
  dotnetSdkVersion: "10.0.x"
  buildConfiguration: Release
  serviceConnection: wi-az400-dev # Workload Identity Federation connection
  appPath: src/services/catalog-service/api/
  appService: catalog-service-terraform
  terraformPath: infra/terraform
  rg: az400-dev
  loc: westeurope
  subscriptionId: cd091145-5ea2-4703-ba5d-41063b1d4308
  adoEnvironment: "05-03-catalog-ci-cd-terraform-env"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build Application
    jobs:
      - job: Build
        displayName: Build .NET Application
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)
              project: catalog-service

  - stage: TerraformPlan
    displayName: Terraform Plan
    dependsOn: Build
    jobs:
      - job: Plan
        displayName: Run Terraform Plan
        steps:
          - template: templates/t-terraform-plan.yaml
            parameters:
              serviceConnection: $(serviceConnection)
              workingDirectory: $(terraformPath)
              subscriptionId: $(subscriptionId)
              appService: $(appService)
              rg: $(rg)
              loc: $(loc)
              planFile: tfplan

          - task: PublishPipelineArtifact@1
            displayName: Publish Terraform Plan
            inputs:
              targetPath: $(terraformPath)
              artifactName: terraform-plan
              publishLocation: pipeline

  - stage: TerraformApply
    displayName: Terraform Apply
    dependsOn: TerraformPlan
    condition: succeeded()
    jobs:
      - deployment: ApplyInfrastructure
        displayName: Apply Terraform Configuration
        environment: $(adoEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: Download Build Artifacts
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureWebApp@1
                  displayName: Deploy to Azure Web App
                  inputs:
                    azureSubscription: $(serviceConnection)
                    appType: "webApp"
                    appName: "$(appService)"
                    package: "$(System.ArtifactsDirectory)/drop/$(buildConfiguration)/*.zip"
                    deploymentMethod: "auto"
