name: "03-02-catalog-api-ci-cd"

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "10.0.x"
  buildConfiguration: Release
  releaseBranchName: master
  serviceConnection: wi-az400-dev
  appPath: src/services/catalog-service/api/
  appService: food-catalog-api-yaml
  adoEnvironment: "03-02-catalog-api-ci-cd-env"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      - job: "Build"
        displayName: "Build job"
        steps:
          - template: ../templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)
              project: catalog-service

  - stage: "Deploy"
    displayName: "Deploy"
    dependsOn: [Build]

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to App Service YAML
        environment: $(adoEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appService)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(serviceConnection)
                    appType: "webApp"
                    WebAppName: $(appService)
                    packageForLinux: "$(Agent.BuildDirectory)/**/*.zip"
