name: 05-01-catalog-provision-ci-cd-cli

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "10.0.x"
  buildConfiguration: Release
  serviceConnection: wi-az400-dev
  folder: src/services/catalog-service/api
  appService: foodcatalog-cli
  environment: dev
  adoEnvironment: "05-01-catalog-provision-ci-cd-cli-env"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: BuildProvision
    displayName: Build and Provision
    jobs:
      - job: Build
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(folder)
              project: catalog-service

      - job: Provision
        steps:
          - task: AzureCLI@2
            displayName: "Provision AppService"
            inputs:
              azureSubscription: "$(serviceConnection)"
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "$(System.DefaultWorkingDirectory)/infra/cli/create-api.sh"
              arguments: "$(environment) $(appService)"

  - stage: Deploy
    displayName: Deploy
    dependsOn: BuildProvision

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: $(adoEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appService)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(serviceConnection)
                    appType: "webApp"
                    WebAppName: $(appService)
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
