name: 04-03-catalog-api-cicd-appcfg

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

variables:
  buildConfiguration: Release
  serviceConnection: wi-az400-dev
  appPath: src/services/catalog-service/api/
  appService: food-catalog-api-yaml
  appConfigEP: "https://foodconfig-dev.azconfig.io"
  configLabel: "dev"
  configKeys: "*"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Transform Config and Build
        steps:
          - task: AzureAppConfiguration@8
            displayName: Read App Config
            inputs:
              azureSubscription: $(serviceConnection)
              AppConfigurationEndpoint: $(appConfigEP)
              KeyFilter: $(configKeys)
              Label: $(configLabel)
          - task: FileTransform@2
            displayName: Transform appsettings.json with App Config variables
            inputs:
              folderPath: $(System.DefaultWorkingDirectory)/$(appPath)
              jsonTargetFiles: appsettings.json
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)
              project: catalog-service
