name: 05-02-catalog-ci-cd-bicep

trigger: none
pr: none

variables:
  dotnetSdkVersion: "10.0.x"
  buildConfiguration: Release
  releaseBranchName: main
  serviceConnection: wi-az400-dev # Workload Identity Federation connection
  appPath: src/services/catalog-service/api/
  appService: catalog-service-bicep
  templateFile: infra/bicep/webapp-windows.bicep
  rg: az400-dev
  loc: "westeurope"
  subscriptionId: cd091145-5ea2-4703-ba5d-41063b1d4308
  adoEnvironment: "05-02-catalog-ci-cd-bicep-env"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build Application
    jobs:
      - job: Build
        displayName: Build .NET Application
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)
              project: catalog-service

  - stage: Provision
    displayName: Provision Infrastructure
    dependsOn: Build
    jobs:
      - job: ProvisionInfra
        displayName: Deploy Bicep Template
        steps:
          - task: AzureCLI@2
            displayName: Deploy Bicep to Azure
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group create \
                  --resource-group $(rg) \
                  --template-file $(templateFile) \
                  --parameters webAppName=$(appService)

  - stage: Deploy
    displayName: Deploy Application
    dependsOn: Provision
    condition: succeeded()
    jobs:
      - deployment: DeployAppService
        displayName: Deploy to App Service
        environment: $(adoEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: Download Build Artifacts
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureWebApp@1
                  displayName: Deploy to Azure Web App
                  inputs:
                    azureSubscription: $(serviceConnection)
                    appType: "webApp"
                    appName: "$(appService)"
                    package: "$(System.ArtifactsDirectory)/drop/$(buildConfiguration)/*.zip"
                    deploymentMethod: "auto"
