name: food-app-common-ci-cd-artifacts

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/food-app-common/*

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  proj: az-400
  feed: food-packages
  dotnetSdkVersion: "9.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  appPath: src/services/food-app-common/

stages:
  - stage: BuildToFeed
    jobs:
      - job: BuildToFeed
        displayName: "Build to Feed"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(appPath)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(appPath)/*.csproj"

          - task: DotNetCoreCLI@2
            inputs:
              command: "pack"
              packagesToPack: "$(appPath)/*.csproj"
            displayName: Create nuget package

          - task: NuGetCommand@2
            displayName: Publish nuget package
            inputs:
              command: "push"
              packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
              nuGetFeedType: "internal"
              publishVstsFeed: "$(proj)/$(feed)"
              allowPackageConflicts: true
