name: 05-02-food-app-iac

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  serviceConnection: wi-az400-dev
  grp: az400-dev
  vault: az400-vault-dev
  templateFile: infra/bicep/food-app.bicep

stages:
  - stage: "Provision"
    jobs:
      - job: "Provision"
        steps:
          - task: AzureKeyVault@1
            displayName: "Azure Key Vault: $(vault)"
            inputs:
              azureSubscription: $(serviceConnection)
              KeyVaultName: $(vault)
          - task: AzureCLI@2
            displayName: "Provision AppService"
            inputs:
              azureSubscription: "$(serviceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group create --resource-group $(grp) \
                  --template-file $(templateFile) \
                  --parameters \
                    appName=food-app-dev \
                    grpLocation=westeurope \
                    acaEnvName= az400acrdev \
                    acrName=$(acrName) \
                    acrPwd=$(acrPassword) \
                    catalogName='catalog-service' \
                    catalogImage='catalog-service' \
                    shopName='food-shop' \
                    shopImage='food-shop' \
                    orderName='order-service' \
                    orderImage='order-service'
