name: "food-app-common-ci-cd-artifacts"

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  proj: az-400
  feed: food-packages
  dotnetSdkVersion: "10.0.100"
  packageVersion: "1.0.$(Build.BuildId)"
  buildConfiguration: Release
  releaseBranchName: master
  appPath: src/services/food-app-common/

stages:
  - stage: BuildToFeed
    jobs:
      - job: BuildToFeed
        displayName: "Build to Feed"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET SDK $(dotnetSdkVersion)"
            inputs:
              packageType: sdk
              version: "$(dotnetSdkVersion)"

          - task: NuGetAuthenticate@1
            displayName: "Authenticate to feeds"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(appPath)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(appPath)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Run unit tests"
            inputs:
              command: "test"
              projects: "$(appPath)/*.csproj"
              arguments: "--no-build --configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "Pack NuGet package"
            inputs:
              command: "pack"
              packagesToPack: "$(appPath)/*.csproj"
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(packageVersion)"

          - task: PublishPipelineArtifact@1
            displayName: "Publish package artifact"
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifact: "nuget-packages"

          - task: DotNetCoreCLI@2
            displayName: "Publish nuget package to feed (dotnet)"
            inputs:
              command: "custom"
              custom: "nuget"
              arguments: >
                push "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
                --source "$(System.CollectionUri)$(System.TeamProject)/_packaging/$(feed)/nuget/v3/index.json"
                --api-key VSTS
            condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
