name: food-shop ci

trigger: none
pr: none

variables:
  nodeVer: "22.12.0"
  dist: food-shop
  pkg: food-shop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build

    jobs:
      - job: Build
        displayName: Build Angular

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVer)
            displayName: Install Node $(nodeVer)

          - script: npm install
            displayName: "Install Packages"

          - script: npm run build
            displayName: "Build"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "dist/$(dist)"
              ArtifactName: $(pkg)
              publishLocation: "Container"
            displayName: "Publish Artifacts"
