name: ui-build-deploy-k8s

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-ui/*

trigger: none      

variables:  
  conACR: conACR
  acr: integrationsonline.azurecr.io
  conKube: foodapp-staging-foodcluster-31852-staging-1644620442182
  img: foodui
  yml: $(Pipeline.Workspace)/s/az-manifests/foodui.yaml
  tag: $(Build.BuildId)
  ns: staging
  imagePullSecret: "secret"
  env: foodapp-staging

pool:
  vmImage: "ubuntu-20.04"
  # name: aci-pool  

stages:
  - stage: "Prepare"
    displayName: "Build UI Img"    
    jobs:
      - job: BuildImg
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(conACR)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: $(img)
              command: buildAndPush
              Dockerfile: food-ui/dockerfile
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(conACR)
          - publish: "$(Build.SourcesDirectory)/manifests"
            artifact: manifests

  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        displayName: Deploy Job
        environment: $(env)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: $(conKube)
                    namespace: '$(ns)'
                    secretType: 'dockerRegistry'
                    secretName: '$(imagePullSecret)'
                    dockerRegistryEndpoint: '$(conACR)'
                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: $(conKube)
                    manifests: '$(yml)'
                    containers: '$(acr)/$(img):$(tag)'
                    imagePullSecrets: '$(imagePullSecret)'
