name: orders-ci-docker-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/order-service/*

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  acr: scACR
  appPath: src/services/order-service/
  imageName: "order-service"
   feedUrl: https://pkgs.dev.azure.com/integrationsonline/az-400/_packaging/food-packages/nuget/v3/index.json

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        steps:
          - task: PowerShell@2
            displayName: "Create and Set PAT Token Variable"
            inputs:
              targetType: "inline"
              script: |
                # Use the System.AccessToken which is available in the pipeline
                $patToken = "$(System.AccessToken)"

                # Set it as a pipeline variable for use in subsequent tasks
                Write-Host "##vso[task.setvariable variable=PATToken;issecret=true]$patToken"
                Write-Host "PAT Token variable has been set"
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: $(acr)
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: "$(appPath)dockerfile"
              tags: "latest"
               arguments: "--build-arg PAT=$(PATToken) --build-arg FEED_URL=$(feedUrl)"

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)
