name: 07-02-orders-ci-docker-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/order-service/*

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  acr: scACR
  appPath: src/services/order-service/
  imageName: "order-service"
  feedUrl: https://pkgs.dev.azure.com/integrationsonline/az-400/_packaging/food-packages/nuget/v3/index.json

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        steps:
          - task: NuGetAuthenticate@1
            displayName: "Authenticate to Azure Artifacts"

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build Image
            inputs:
              command: build
              repository: "$(imageName)"
              dockerfile: "$(appPath)dockerfile"
              tags: "latest"
              arguments: "--build-arg PAT=$(System.AccessToken)"
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

          - task: Docker@2
            displayName: Push Image
            inputs:
              containerRegistry: $(acr)
              repository: "$(imageName)"
              command: push
              tags: "latest"

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)
