name: 05-01-orders-iac-cli

trigger: none
pr: none

variables:
  script: "infra/cli/create-orders-topic-func.sh"
  serviceConnection: wi-az400-dev
  environment: dev

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: IaC
    displayName: "Infrastructure as Code"
    jobs:
      - job: IaC
        displayName: IaC Azure CLI
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: "bash"
              scriptLocation: "scriptPath"
              scriptPath: "$(System.DefaultWorkingDirectory)/$(script)"
              arguments: "$(environment)"
