name: payment-py-ci-cd

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/functions/payment-py/*

trigger: none
pr: none

variables:
  azureSubscription:
  functionAppName: "payment-func-py-app"
  pythonVersion: "3.11"

stages:
  - stage: Build
    displayName: "Build Python Function"
    jobs:
      - job: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
          - script: |
              python -m pip install --upgrade pip
              pip install -r src/functions/payment-py/requirements.txt
            displayName: "Install dependencies"
          - script: |
              cd src/functions/payment-py
              if [ -f "test" ] || [ -d "tests" ]; then
                pytest
              else
                echo "No tests found. Skipping."
              fi
            displayName: "Run tests"
          - script: |
              cd src/functions/payment-py
              zip -r ../../payment-func-py.zip .
            displayName: "Archive function app"
          - publish: src/payment-func-py.zip
            artifact: functionapp

  - stage: Deploy
    displayName: "Deploy to Azure Function App"
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: "dev"
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: functionapp
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az functionapp deployment source config-zip \
                        --resource-group $(resourceGroup) \
                        --name $(functionAppName) \
                        --src $(Pipeline.Workspace)/functionapp/payment-func-py.zip
                  displayName: "Deploy Function App"
