name: "03-02-payment-func-py-ci-cd"

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/az-functions/payment-py/*

trigger: none
pr: none

variables:
  serviceConnection: wi-az400-dev
  functionAppName: "payment-func-py-app"
  pythonVersion: "3.12"
  adoEnvironment: "03-02-payment-func-py-ci-cd"
  resourceGroup: "az400-dev-rg"
  azureSubscription: "wi-az400-dev"

stages:
  - stage: Build
    displayName: "Build Python Function"
    jobs:
      - template: templates/t-build-func-py.yaml
        parameters:
          pythonVersion: $(pythonVersion)
          appPath: src/az-functions/payment-py
          requirementsPath: src/az-functions/payment-py/requirements.txt
          artifactName: payment-func-py

  - stage: Deploy
    displayName: "Deploy to Azure Function App"
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: $(adoEnvironment)
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: functionapp
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az functionapp deployment source config-zip \
                        --resource-group $(resourceGroup) \
                        --name $(functionAppName) \
                        --src $(Pipeline.Workspace)/functionapp/payment-func-py.zip
                  displayName: "Deploy Function App"
