name: "02-02-python-mcp-ci"

# trigger:
#   branches:
#     include:
#     - main
#   paths:
#     include:
#     - src/ai/youtube-transcriber-mcp-py/**

trigger: none
pr: none

variables:
  pythonVersion: "3.11"
  appRoot: "src/ai/youtube-transcriber-mcp-py"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and Test Python MCP Server

    jobs:
      - job: BuildAndTest
        displayName: Build and Test

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
            displayName: "Use Python $(pythonVersion)"

          - script: python -m pip install --upgrade pip
            displayName: "Upgrade pip"

          - script: pip install -r $(System.DefaultWorkingDirectory)/$(appRoot)/requirements.txt
            displayName: "Install Dependencies"

          - script: |
              pip install pytest pytest-cov flake8
            displayName: "Install Testing Tools"

          - script: |
              cd $(System.DefaultWorkingDirectory)/$(appRoot)
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            displayName: "Lint with flake8 (Critical errors)"
            continueOnError: true

          - script: |
              python -m pytest --version
            displayName: "Check pytest installation"
            continueOnError: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(System.DefaultWorkingDirectory)/$(appRoot)"
              ArtifactName: "python-mcp-server"
              publishLocation: "Container"
            displayName: "Publish Artifacts"
