name: react-ci-docker-img.yml

trigger: none
pr: none

variables:
  imageName: react-devops
  acr: conACR
  appRoot: src/react/react-devops

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "BuildImg"
    displayName: "Build React Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: $(appRoot)/Dockerfile
              buildContext: $(appRoot)

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)
