name: 03-02-spfx-ci-cd-template

trigger: none
pr: none

variables:
  package: foodlist-wp.sppkg
  packageLocation: /drop/src/teams/food-list/sharepoint/solution
  appPath: src/teams/food-list/
  nodeVersion: "14.x"
  serviceConnection: "wi-az400"
  adoEnvironment: "m365-integrationsonline"
  appId: 5e8ecccb-da70-40af-808f-4860a1571f4d
  tenantId: d92b247e-90e0-4469-a129-6a32866c0d0a
  # set pipeline vars: username, password

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: Build SPFx Package
        steps:
          - template: templates/t-spfx-build.yaml
            parameters:
              nodeVersion: $(nodeVersion)
              pkg: $(package)
              fld: $(appPath)

  - stage: Deploy
    displayName: Deploy to M365
    dependsOn: Build
    jobs:
      - deployment: DeployM365
        displayName: Deploy to M365
        environment: $(adoEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/t-spfx-deploy-cli.yaml
                  parameters:
                    nodeVersion: $(nodeVersion)
                    pkg: $(package)
                    pkgLocation: $(packageLocation)
                    username: $(username)
                    password: $(password)
                    appId: $(appId)
                    tenantId: $(tenantId)
