name: "03-02-utils-func-node-ci-cd"

trigger: none
pr: none

variables:
  serviceConnection: wi-az400-dev
  functionAppName: utils-func-node-dev
  appPath: src/az-functions/utils-ts/
  adoEnvironment: "03-02-utils-func-node-ci-cd"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: templates/t-build-func-node.yaml
        parameters:
          nodeVersion: "22.x"
          appPath: $(appPath)
          artifactName: $(Build.BuildId)

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: $(adoEnvironment)
        displayName: Deploy Function to AppService
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@2
                  displayName: "Azure Functions App Deploy"
                  inputs:
                    connectedServiceNameARM: $(serviceConnection)
                    appType: functionAppLinux
                    appName: $(functionAppName)
                    package: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
