apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodapi
  template:
    metadata:
      labels:
        app: foodapi                 
    spec:
      containers:
      - name: foodapi
        image: arambazamba/foodapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "1"
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: foodapi
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: foodapi
---
