parameters:
  - name: con
    type: string
    default: ""

  - name: img
    type: string
    default: ""

  - name: path
    type: string
    default: ""    

steps:
- task: Docker@2
  displayName: "Login to ACR"
  inputs:
    command: "login"
    containerRegistry: "${{ parameters.con }}"

- task: Docker@2
  displayName: "Build and Push"
  inputs:
    repository: "${{ parameters.img }}"
    command: "buildAndPush"
    Dockerfile: "${{ parameters.path }}dockerfile"

- task: Docker@2
  displayName: "Logout of ACR"
  inputs:
    command: "logout"
    containerRegistry: "${{ parameters.con }}"
