name: custom-agent-spfx

trigger: none

pool:
  name: custom-agents

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 22.x
            displayName: Use Node 22.x

          - task: CmdLine@2
            displayName: npm install
            inputs:
              script: "npm install"

          - task: CmdLine@2
            displayName: "npm run build"
            inputs:
              script: |
                npm run build

          - task: CmdLine@2
            displayName: "package solution (if present)"
            inputs:
              script: |
                if npm run 2>&1 | grep -q package-solution; then
                  npm run package-solution
                else
                  echo 'package-solution script not present, skipping'
                fi
