# trigger:
#   branches:
#     include:
#       - master    
#   paths:
#     include:
#       - SomePath

trigger: none

variables:
  # exectJob used in condition is defined as pipeline var
  # inline syntax
  provision: true
  # two line syntax
  name: somevar
  value: somevarvalue
  
  # enable debugging
  System.Debug: true

pool:
  vmImage: "ubuntu-latest"

# use a selfhosted pool
# pool:
#     name: linux-selfhosted

stages:
  - stage: stageA
    jobs:
      - job: stageAJobA
        # pool:
          # vmImage: "ubuntu-latest"

        steps:
          - task: Bash@3
            displayName: stageA-jobA
            inputs:
              targetType: 'inline'
              script: echo 'Executing JobA'
                    
      - job: stageAJobB
        dependsOn: []
        # pool:
        #   vmImage: "ubuntu-latest"

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo 'Executing JobB'

  - stage: stageB
    dependsOn: stageA   
    # pool:
    #   vmImage: "ubuntu-latest"

    jobs:
      - job: stageBJobA

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo 'Executing JobA'
  

      - job: stageBJobB
        condition: eq(variables.exectJob, true)

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo 'Executing JobB'