##### Stage 1 - Create the build-image
FROM node:22.14.0-alpine as build
LABEL author="Alexander Kastil"

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

##### Stage 2 - Create the run-time-image
FROM nginx:alpine
VOLUME /var/cache/nginx

# Take output from node build
COPY --from=build /app/dist/angular-devops/browser/ /usr/share/nginx/html
# Add nginx url rewriteconfig
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

# docker build --rm -f dockerfile -t food-shop .

