name: pipeline-ressources-var-grps

trigger: none
pr: none

variables:
- group: az400-variables

stages:

- stage: OutputVars

  jobs: 

  - job: ConsumeVars
    dependsOn: []
    
    steps:
    - bash: |
        echo "node-version:"
        echo $(node-version)
      name: nodeversion
      displayName: Output Node Version