parameters:
  - name: nodeVersion
    type: string
    default: "22.x"
  - name: appPath
    type: string
  - name: artifactName
    type: string

jobs:
  - job: Build
    displayName: "Build Node.js Function"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "${{ parameters.nodeVersion }}"
        displayName: "Install Node.js"

      - script: |
          npm install
          npm run build --if-present
          npm run test --if-present
        displayName: "Prepare binaries"
        workingDirectory: ${{ parameters.appPath }}

      - task: ArchiveFiles@2
        displayName: "Archive files"
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}.zip
          replaceExistingArchive: true

      - publish: $(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}.zip
        artifact: drop
