parameters:
  - name: acrName
    type: string
  - name: image
    type: string
  - name: app
    type: string
  - name: grp
    type: string
  - name: serviceConnection
    type: string
  - name: acaenv
    type: string
  - name: targetPort
    type: number
    default: 80

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy to ACA
        steps:
          - checkout: none
          - task: AzureCLI@2
            displayName: Fetch ACR credentials
            inputs:
              azureSubscription: "${{ parameters.serviceConnection }}"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Fetch ACR admin credentials and surface password as pipeline variable
                ACR_PASSWORD=$(az acr credential show --name ${{ parameters.acrName }} --query "passwords[0].value" -o tsv)
                echo "##vso[task.setvariable variable=acrPassword;issecret=true]${ACR_PASSWORD}"

          - task: AzureCLI@2
            displayName: Deploy to Azure Container Apps
            inputs:
              azureSubscription: "${{ parameters.serviceConnection }}"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Create or update the container app
                if az containerapp show -n ${{ parameters.app }} -g ${{ parameters.grp }} &>/dev/null; then
                  echo "Updating existing container app..."
                  az containerapp update -n ${{ parameters.app }} -g ${{ parameters.grp }} --image ${{ parameters.image }}
                else
                  echo "Creating new container app..."
                  az containerapp create -n ${{ parameters.app }} -g ${{ parameters.grp }} --image ${{ parameters.image }} \
                    --environment ${{ parameters.acaenv }} \
                    --target-port ${{ parameters.targetPort }} \
                    --ingress external \
                    --registry-server ${{ parameters.acrName }}.azurecr.io \
                    --registry-username ${{ parameters.acrName }} \
                    --registry-password $(acrPassword)
                fi
