name: blob-console-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/jobs/blob-spring/*

trigger: none      
pr: none

variables:
  path: src/jobs/blob-spring/
  imageName: blob-spring
  acr: conACR

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "BuildImg"
    displayName: "Build Catalog Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(path)dockerfile'

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)
