name: catalog-ci-cd-tf

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none

variables:
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  appPath: src/services/catalog-service/api/
  appService: food-catalog-api-yaml

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: BnP
    displayName: Build and Provision
    jobs:
      - job: "Build"
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)
      
      - job: Provision
        steps:        
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Install Terraform 0.12.3'

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
        displayName: 'Terraform : azurerm'
        inputs:
          backendServiceArm: 'Visual Studio Enterprise (78033352-805c-4acd-af80-f8f95083268d)'
          backendAzureRmResourceGroupName: 'az400-tf-24892'
          backendAzureRmStorageAccountName: tfstorage24892
          backendAzureRmContainerName: terraform
          backendAzureRmKey: 'KRLK8NrOUZ6OQz3L5WRBxbsPZKe1KffuVg7pFMAhLpI8NBBrsja0fisik+XBrpf1yHAPuwRt+fQq2Q1Y5BQWXA=='


  - stage: Deploy
    displayName: Deploy
    dependsOn: BnP

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: "$(appservice)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
