name: catalog-build-docker-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none      
pr: none

variables:
  appPath: src/services/catalog-service/api/
  imageName: 'catalog-service:latest'
  acr: conACR

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "Build"
    displayName: "Build Catalog Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)
          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(appPath)dockerfile'
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)
