name: 03-01-catalog-cd-aca-task

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  acrName: 'az400acrdev'
  image: 'az400acrdev.azurecr.io/catalog-service'
  app: 'catalog-service-v1'
  grp: 'az400-dev'
  acaenv: 'az400acaenv'

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy to ACA
        steps:
        - task: AzureContainerApps@1
          inputs:
            azureSubscription: 'scFood'
            acrName: 'az400acrdev.azurecr.io'
            acrUsername: '$(acrName)'
            acrPassword: '$(acaPassword)'
            imageToDeploy: '$(image)'
            containerAppName: '$(app)'
            resourceGroup: '$(grp)'
            containerAppEnvironment: '$(acaenv)'