name: 03-01-catalog-cd-aca

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy to ACA
        steps:
        - task: AzureContainerApps@1
          inputs:
            azureSubscription: 'scFood'
            acrName: 'az400acrdev'
            acrUsername: 'az400acrdev'
            acrPassword: $(acaPassword)
            imageToDeploy: 'az400acrdev.azurecr.io/catalog-service'
            containerAppName: 'catalog-service-v1'
            resourceGroup: 'az400-dev'
            containerAppEnvironment: 'az400acaenv'