name: docker-ci-img

# trigger:
#   branches:
#     include:
#       - master

trigger: none
pr: none

variables:
  appPath: src/web/food-shop/
  imageName: food-shop
  acr: conACR

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "BuildImg"
    displayName: "Build Catalog Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(appPath)dockerfile'

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)