name: Deploy UI to Static Website

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-ui/*

trigger: none

variables:
  loc: food-ui/
  apiurl: https://foodapi-030.azurewebsites.net

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: BuildAndDeploy

    jobs:
      - job: BuildAndDeploy

        steps:
          - checkout: self
            submodules: true

          - task: AzureKeyVault@1
            inputs:
              azureSubscription: "azFoodApp"
              KeyVaultName: "foodvault-030"
              SecretsFilter: "*"
              RunAsPreJob: true

          - task: FileTransform@1
            displayName: Replace Api Url
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/**/assets'
              fileType: 'json'
              targetFiles: '**/app-config.json'
              
          - task: CmdLine@2
            displayName: Verify Url
            inputs:
              script: |
                cat $(System.DefaultWorkingDirectory)/FoodUI/src/assets/app-config.json

          - task: AzureStaticWebApp@0
            inputs:
              app_location: /$(loc)
              api_location: ""
              output_location: dist/food-ui
              app_build_command: npm run build-prod
            env:
              azure_static_web_apps_api_token: $(swDeploymentToken)
