name: provision-azure-cli

trigger: none
pr: none

variables:
  scriptPath: "deploy/cli/create-orders-topic-func.sh"
  azSubscription: scFood
  environment: staging

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Provision
    jobs:
      - job: Provision
        displayName: Provision Azure CLI
        steps:
          - checkout: none
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'scFood'
              scriptType: 'bash'
              scriptPath: $(scriptPath)
              arguments: $(environment)