name: catalog-ci-cd-tf

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  appPath: src/services/catalog-service/api/
  appService: food-catalog-api-yaml

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Provision
    displayName: Provision Terraform
    jobs:
      - job: Provision
        steps:        
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Install Terraform 0.12.3'

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
        displayName: 'Terraform : azurerm'
        inputs:
          backendServiceArm: 'Visual Studio Enterprise (78033352-805c-4acd-af80-f8f95083268d)'
          backendAzureRmResourceGroupName: 'az400-tf-24892'
          backendAzureRmStorageAccountName: tfstorage24892
          backendAzureRmContainerName: terraform
          backendAzureRmKey: 'KRLK8NrOUZ6OQz3L5WRBxbsPZKe1KffuVg7pFMAhLpI8NBBrsja0fisik+XBrpf1yHAPuwRt+fQq2Q1Y5BQWXA=='